# Netlify Configuration
[build]
  base = "client/"
  publish = "dist/"
  command = "npm run build"

# Redirect rules
[[redirects]]
  from = "/"
  to = "/redirect.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404