name: Deploy Backend to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Railway
        run: |
          curl -X POST https://railway.app/api/deploy \\
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \\
            -d '{"projectId": "${{ secrets.RAILWAY_PROJECT_ID }}"}'