name: Deploy to Netlify and Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install client dependencies
        run: |
          cd client
          npm install
      
      - name: Build client
        run: |
          cd client
          npm run build
          
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=client/dist --prod

  deploy-server:
    runs-on: ubuntu-latest
    needs: deploy-client
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install server dependencies
        run: |
          cd server
          npm install
          
      - name: Deploy to Railway
        uses: railwayapp/actions/cli@v1
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          railway-project: ${{ secrets.RAILWAY_PROJECT_ID }}